// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2cIFrTO7KjaX2QCly0ZDZ4ucQyczpYvM',
    appId: '1:850450528914:web:c6d8664400e5d13775c44b',
    messagingSenderId: '850450528914',
    projectId: 'elearninf',
    authDomain: 'elearninf.firebaseapp.com',
    databaseURL: 'https://elearninf-default-rtdb.firebaseio.com',
    storageBucket: 'elearninf.appspot.com',
    measurementId: 'G-B763Y458CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Ypm56OnXTaGBk8QHCBu8GsVSyzTTKQo',
    appId: '1:850450528914:android:6f1012f2d504e9db75c44b',
    messagingSenderId: '850450528914',
    projectId: 'elearninf',
    databaseURL: 'https://elearninf-default-rtdb.firebaseio.com',
    storageBucket: 'elearninf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUdYk8i4ii4Y3KMfsMab0ylJE6Bj_HY-8',
    appId: '1:850450528914:ios:8e5c80ac1347257775c44b',
    messagingSenderId: '850450528914',
    projectId: 'elearninf',
    databaseURL: 'https://elearninf-default-rtdb.firebaseio.com',
    storageBucket: 'elearninf.appspot.com',
    androidClientId: '850450528914-00orp5v8e47ghc3dla4pdlprenq7ob3l.apps.googleusercontent.com',
    iosClientId: '850450528914-23s9hfs88eogtr2uc9nuv85b1nnbhgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.car',
  );
}
